language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t fgigante/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fgigante/react-test npm test

after_success:
  - docker build -t fgigante/multi-client ./client
  - docker build -t fgigante/multi-nginx ./nginx
  - docker build -t fgigante/multi-server ./server
  - docker build -t fgigante/multi-worker ./worker
